"""V2 CRM login data journey 

Revision ID: 1bd696a3e70d
Revises: f6ecdf75b495
Create Date: 2026-03-22 18:47:50.317987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bd696a3e70d"
down_revision: Union[str, None] = 'f6ecdf75b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###