"""V2 CRM catalogue 

Revision ID: 387f8b01769a
Revises: 1bd696a3e70d
Create Date: 2026-03-23 01:47:50.641293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "387f8b01769a"
down_revision: Union[str, None] = '1bd696a3e70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('custom_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.tva_intra_com'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'catalog_item_id', name='uq_cci_company_catalog_item')
    )
    op.create_table('attribu_produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category_translations')
    op.drop_table('product_components')
    # On retire d'abord les FK restantes vers `categories`, sinon Postgres bloque le DROP.
    # Noms de contraintes attendus (Postgres) d'après l'erreur :
    # - services_category_id_fkey (services -> categories)
    # - products_category_id_fkey (products -> categories)
    # On force via SQL pour éviter les divergences de naming convention.
    op.execute(
        sa.text(
            "ALTER TABLE services DROP CONSTRAINT IF EXISTS services_category_id_fkey"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_id_fkey"
        )
    )
    op.drop_table('categories')
    op.add_column('catalog_items', sa.Column('service_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('catalog_items_company_id_fkey'), 'catalog_items', type_='foreignkey')
    op.drop_constraint(op.f('catalog_items_product_id_fkey'), 'catalog_items', type_='foreignkey')
    op.create_foreign_key(None, 'catalog_items', 'services', ['service_id'], ['id'])
    op.drop_column('catalog_items', 'custom_price')
    op.drop_column('catalog_items', 'currency')
    op.drop_column('catalog_items', 'company_id')
    op.drop_column('catalog_items', 'stock_quantity')
    op.drop_column('catalog_items', 'product_id')
    op.drop_column('catalog_items', 'is_available')
    op.add_column('catalogs', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'catalogs', 'catalogs', ['parent_id'], ['id'])
    op.add_column('products', sa.Column('catalog_item_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('companies_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'products', ['catalog_item_id'])
    # FK produits -> categories déjà retirée plus haut.
    op.create_foreign_key(None, 'products', 'catalog_items', ['catalog_item_id'], ['id'])
    op.create_foreign_key(None, 'products', 'companies', ['companies_id'], ['tva_intra_com'])
    op.drop_column('products', 'category_id')
    op.add_column('reviews', sa.Column('company_id', sa.String(length=32), nullable=False))
    op.drop_constraint(op.f('reviews_service_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'companies', ['company_id'], ['tva_intra_com'])
    op.drop_column('reviews', 'product_id')
    op.drop_column('reviews', 'service_id')
    op.add_column('services', sa.Column('service_type', sa.String(length=64), nullable=True))
    # FK services -> categories déjà retirée plus haut.
    op.drop_column('services', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('services_category_id_fkey'), 'services', 'categories', ['category_id'], ['id'])
    op.drop_column('services', 'service_type')
    op.add_column('reviews', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_product_id_fkey'), 'reviews', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('reviews_service_id_fkey'), 'reviews', 'services', ['service_id'], ['id'])
    op.drop_column('reviews', 'company_id')
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'companies_id')
    op.drop_column('products', 'catalog_item_id')
    op.drop_constraint(None, 'catalogs', type_='foreignkey')
    op.drop_column('catalogs', 'parent_id')
    op.add_column('catalog_items', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('catalog_items', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('catalog_items', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('catalog_items', sa.Column('company_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('catalog_items', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('custom_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'catalog_items', type_='foreignkey')
    op.create_foreign_key(op.f('catalog_items_product_id_fkey'), 'catalog_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('catalog_items_company_id_fkey'), 'catalog_items', 'companies', ['company_id'], ['tva_intra_com'])
    op.drop_column('catalog_items', 'service_id')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('categories_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_table('product_components',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], name=op.f('product_components_component_id_fkey')),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], name=op.f('product_components_parent_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_components_pkey'))
    )
    op.create_table('category_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('category_translations_category_id_fkey')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('category_translations_language_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('category_translations_pkey'))
    )
    op.drop_table('product_price_history')
    op.drop_table('attribu_produit')
    op.drop_table('company_catalog_items')
    # ### end Alembic commands ###