"""adresses gestion

Revision ID: 724835dc71eb
Revises: 387f8b01769a
Create Date: 2026-03-27 15:36:36.297589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "724835dc71eb"
down_revision: Union[str, None] = '387f8b01769a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attribut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_shipping')
    op.drop_table('order_items')
    op.drop_table('attribu_produit')
    op.drop_table('company_translations')
    op.drop_table('order_addresses')
    op.add_column('addresses', sa.Column('intra_com', sa.String(length=32), nullable=True))
    op.drop_column('addresses', 'intra_communal')
    op.add_column('companies', sa.Column('VAT_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('invoice_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'addresses', ['invoice_address_id'], ['id'])
    op.add_column('products', sa.Column('teinte', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('type_de_produit', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('gamme', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('duree_garantie', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('conditions_garantie', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('piece_ouvrage_destination', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('traitement_bois_classification', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('produit_nuance', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description_profil', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('couleur_traitement_autoclave', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('code_douane_sh8', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('type_bois', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('essence_bois', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('longueur', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('largeur', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('hauteur', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('products', sa.Column('volume', sa.Numeric(precision=12, scale=5), nullable=True))
    op.add_column('products', sa.Column('poids_net', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'poids_net')
    op.drop_column('products', 'volume')
    op.drop_column('products', 'hauteur')
    op.drop_column('products', 'largeur')
    op.drop_column('products', 'longueur')
    op.drop_column('products', 'essence_bois')
    op.drop_column('products', 'type_bois')
    op.drop_column('products', 'code_douane_sh8')
    op.drop_column('products', 'couleur_traitement_autoclave')
    op.drop_column('products', 'description_profil')
    op.drop_column('products', 'produit_nuance')
    op.drop_column('products', 'traitement_bois_classification')
    op.drop_column('products', 'piece_ouvrage_destination')
    op.drop_column('products', 'conditions_garantie')
    op.drop_column('products', 'duree_garantie')
    op.drop_column('products', 'gamme')
    op.drop_column('products', 'type_de_produit')
    op.drop_column('products', 'teinte')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'invoice_address_id')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_column('companies', 'VAT_rate')
    op.add_column('addresses', sa.Column('intra_communal', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'intra_com')
    op.create_table('order_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_addresses_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_addresses_pkey'))
    )
    op.create_table('company_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.tva_intra_com'], name=op.f('company_translations_company_id_fkey')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('company_translations_language_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_translations_pkey'))
    )
    op.create_table('attribu_produit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('attribu_produit_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attribu_produit_pkey'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('catalog_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], name=op.f('order_items_catalog_item_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('order_items_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.create_table('product_shipping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('length_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('width_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume_m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('freight_class', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('requires_special_handling', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_shipping_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_shipping_pkey'))
    )
    op.drop_table('product_order')
    op.drop_table('product_attribut')
    # ### end Alembic commands ###