"""add timestamps + improvements

Revision ID: 7f89628c748d
Revises: 8b3ac896043d
Create Date: 2026-02-27 15:26:48.265248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f89628c748d"
down_revision: Union[str, None] = '8b3ac896043d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('supplier_company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('price_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_reserved', sa.Integer(), nullable=False),
    sa.Column('restock_eta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('type', sa.String(length=16), nullable=False))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('deals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('deals', sa.Column('total_gross', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('deals', sa.Column('total_net', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('deals', sa.Column('signed_at', sa.DateTime(), nullable=True))
    op.add_column('deals', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('deals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('deals_company_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_owner_user_id_fkey'), 'deals', type_='foreignkey')
    op.drop_constraint(op.f('deals_contact_id_fkey'), 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'users', ['user_id'], ['id'])
    op.drop_column('deals', 'value_gross')
    op.drop_column('deals', 'next_action_at')
    op.drop_column('deals', 'owner_user_id')
    op.drop_column('deals', 'value_net')
    op.drop_column('deals', 'contact_id')
    op.drop_column('deals', 'company_id')
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index('ix_documents_owner', 'documents', ['tenant_id', 'owner_type', 'owner_id'], unique=False)
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('tenants', 'created_at')
    op.drop_index('ix_documents_owner', table_name='documents')
    op.drop_column('documents', 'created_at')
    op.add_column('deals', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('value_net', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('next_action_at', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('value_gross', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(op.f('deals_contact_id_fkey'), 'deals', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(op.f('deals_owner_user_id_fkey'), 'deals', 'users', ['owner_user_id'], ['id'])
    op.create_foreign_key(op.f('deals_company_id_fkey'), 'deals', 'companies', ['company_id'], ['id'])
    op.drop_column('deals', 'updated_at')
    op.drop_column('deals', 'created_at')
    op.drop_column('deals', 'signed_at')
    op.drop_column('deals', 'total_net')
    op.drop_column('deals', 'total_gross')
    op.drop_column('deals', 'user_id')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'type')
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('carts')
    # ### end Alembic commands ###