"""V1 C RM claude 

Revision ID: c9aff6b57f35
Revises: f3fd9d935d00
Create Date: 2026-03-10 17:50:47.356726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9aff6b57f35"
down_revision: Union[str, None] = 'f3fd9d935d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('freight_class', sa.String(length=32), nullable=True),
    sa.Column('requires_special_handling', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_unit', sa.String(length=16), nullable=True),
    sa.Column('duration_value', sa.Integer(), nullable=True),
    sa.Column('remote_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('zone_from', sa.String(length=64), nullable=True),
    sa.Column('zone_to', sa.String(length=64), nullable=True),
    sa.Column('weight_min_kg', sa.Float(), nullable=True),
    sa.Column('weight_max_kg', sa.Float(), nullable=True),
    sa.Column('volume_max_m3', sa.Float(), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('custom_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('addresses', sa.Column('type', sa.String(length=32), nullable=False))
    op.add_column('addresses', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('addresses', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('addresses', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('addresses', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('addresses_tenant_id_fkey'), 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'address_line1')
    op.drop_column('addresses', 'address_type')
    op.drop_column('addresses', 'country')
    op.drop_column('addresses', 'address_line3')
    op.drop_column('addresses', 'tenant_id')
    op.drop_column('addresses', 'address_line2')
    op.add_column('companies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('role', sa.String(length=32), nullable=False))
    op.add_column('companies', sa.Column('registration_number', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('vat_number', sa.String(length=32), nullable=True))
    op.add_column('companies', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('companies_tenant_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    op.drop_column('companies', 'address_line1')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'siret')
    op.drop_column('companies', 'legal_name')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'type')
    op.drop_column('companies', 'tenant_id')
    op.drop_column('companies', 'naf')
    op.drop_column('companies', 'city')
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_constraint(op.f('orders_tenant_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_deal_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_supplier_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'tenant_id')
    op.drop_column('orders', 'supplier_user_id')
    op.drop_column('orders', 'deal_id')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(length=32), nullable=False))
    op.add_column('products', sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('products', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('products_tenant_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_supplier_company_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'restock_eta')
    op.drop_column('products', 'supplier_company_id')
    op.drop_column('products', 'stock_total')
    op.drop_column('products', 'category')
    op.drop_column('products', 'name')
    op.drop_column('products', 'tenant_id')
    op.drop_column('products', 'stock_reserved')
    op.drop_column('products', 'price_unit')
    op.add_column('users', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('is_vendor', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'role')
    # Suppression des anciennes tables CRM après avoir retiré les FK dépendantes
    # Ordre important à cause des contraintes FK :
    # cart_items -> carts -> documents -> tenants
    op.drop_table('deals')
    op.drop_table('contacts')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_documents_owner'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('carts')
    op.drop_table('tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_vendor')
    op.drop_column('users', 'phone')
    op.add_column('products', sa.Column('price_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('stock_reserved', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('supplier_company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('restock_eta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_supplier_company_id_fkey'), 'products', 'companies', ['supplier_company_id'], ['id'])
    op.create_foreign_key(op.f('products_tenant_id_fkey'), 'products', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'reference_price')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'category_id')
    op.add_column('orders', sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('supplier_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_supplier_user_id_fkey'), 'orders', 'users', ['supplier_user_id'], ['id'])
    op.create_foreign_key(op.f('orders_deal_id_fkey'), 'orders', 'deals', ['deal_id'], ['id'])
    op.create_foreign_key(op.f('orders_tenant_id_fkey'), 'orders', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'user_id')
    op.add_column('companies', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('naf', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('siret', sa.VARCHAR(length=14), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_tenant_id_fkey'), 'companies', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'is_verified')
    op.drop_column('companies', 'vat_number')
    op.drop_column('companies', 'registration_number')
    op.drop_column('companies', 'role')
    op.drop_column('companies', 'user_id')
    op.add_column('addresses', sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('address_line3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('address_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('addresses_tenant_id_fkey'), 'addresses', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('addresses', 'is_primary')
    op.drop_column('addresses', 'lng')
    op.drop_column('addresses', 'lat')
    op.drop_column('addresses', 'country_code')
    op.drop_column('addresses', 'state')
    op.drop_column('addresses', 'street')
    op.drop_column('addresses', 'type')
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('carts_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('carts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pkey'))
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('documents_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_owner'), 'documents', ['tenant_id', 'owner_type', 'owner_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price_snapshot', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('cart_items_cart_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('cart_items_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('contacts_company_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('contacts_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contacts_pkey'))
    )
    op.create_table('deals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_gross', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_net', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('deals_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('deals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deals_pkey'))
    )
    op.drop_table('review_translations')
    op.drop_table('order_items')
    op.drop_table('service_translations')
    op.drop_table('reviews')
    op.drop_table('catalog_items')
    op.drop_table('shipping_rates')
    op.drop_table('services')
    op.drop_table('product_translations')
    op.drop_table('product_shipping')
    op.drop_table('product_components')
    op.drop_table('payments')
    op.drop_table('order_addresses')
    op.drop_table('company_translations')
    op.drop_table('catalogs')
    op.drop_table('user_profiles')
    op.drop_table('category_translations')
    op.drop_table('languages')
    op.drop_table('images')
    op.drop_table('categories')
    # ### end Alembic commands ###